package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Anadir_a_ListaReproduccion_ventana extends VerticalLayout {
	protected VerticalLayout verticalVideoCheck;
	protected VerticalLayout verticalVideo;
	protected VerticalLayout verticalCheck;
	protected CheckBox check;
	protected Button cancelar;
	protected Button confirmar;

	public Anadir_a_ListaReproduccion_ventana() {
		Design.read(this);
	}
}
