package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Buscador_Usuario_ventana extends VerticalLayout {
	protected HorizontalLayout horizontalCabecera;
	protected HorizontalLayout horizontalBuscador;
	protected HorizontalLayout horizontalInicio;
	protected ComboBox<java.lang.String> ordenarPorUs;
	protected Panel panelBuscadorUs;
	protected VerticalLayout verticalBuscadorUs;
	protected HorizontalLayout horizontalResultadoUs;

	public Buscador_Usuario_ventana() {
		Design.read(this);
	}
}
