package diagramaclasesiu;

public class Comentario_Video_Ajeno_A_Propio_AR extends Comentario_Video_Ajeno_R {
	public Visualizacion_Video_Ajeno_A _unnamed_Visualizacion_Video_Ajeno_A_;
	public Visualizacion_Video_Propio_AR _unnamed_Visualizacion_Video_Propio_AR_;
	public Conf_Eliminar_Comentario _unnamed_Conf_Eliminar_Comentario_;
}