package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Comentario2_ventana extends VerticalLayout {
	protected VerticalLayout vComentario;
	protected HorizontalLayout hApodoFoto;
	protected HorizontalLayout hComentario;
	protected TextArea areaComentario;
	protected Button bComentario;

	public Comentario2_ventana() {
		Design.read(this);
	}
}
