package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Link;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Iniciar_Sesion_ventana extends VerticalLayout {
	protected VerticalLayout vIniciar;
	protected TextField tUsuario;
	protected PasswordField tPass;
	protected HorizontalLayout hRec;
	protected Link lPass;
	protected HorizontalLayout hVacio;
	protected Button botonIniciar;

	public Iniciar_Sesion_ventana() {
		Design.read(this);
	}
}
