package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Nuevo_Pass_ventana extends VerticalLayout {
	protected Label nuevaContrasena;
	protected PasswordField contrasena;
	protected PasswordField repetirContrasena;
	protected HorizontalLayout hAccion;
	protected Button cancelar;
	protected Button confirmar;

	public Nuevo_Pass_ventana() {
		Design.read(this);
	}
}
