package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Pag_Inicio_R_ventana extends VerticalLayout {
	protected HorizontalLayout hCabeceraGeneral;
	protected HorizontalLayout hCabeceraIncioBus;
	protected Label videosConMasMeGusta;
	protected Panel panelvideosMG;
	protected HorizontalLayout hPanelVideosMG;
	protected Label ultimosVideosSubidos;
	protected Panel panelUltimosVideosSubidos;
	protected HorizontalLayout hPanelUltimosVideosSubidos;
	protected Label videosRelacionados;
	protected Panel panelVR;
	protected HorizontalLayout hPanelVR;
	protected Label videosOtrosUser;
	protected Panel panelVideosOtrosUser;
	protected HorizontalLayout hPanelVideosOtrosUser;
	protected Label videosVreciente;
	protected Panel panelVideosVreciente;
	protected HorizontalLayout hPanelVideosVreciente;

	public Pag_Inicio_R_ventana() {
		Design.read(this);
	}
}
