public class Pag_Inicio_R extends Pag_Inicio_NR {
	public Cabecera_R _unnamed_Cabecera_R_;
	public Lista_Historial _unnamed_Lista_Historial_;
	public Lista_Videos_Relacionados _unnamed_Lista_Videos_Relacionados_;
	public Lista_Videos_Suscriptores _unnamed_Lista_Videos_Suscriptores_;
}