package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Perfil_Propio_A_ventana extends VerticalLayout {
	protected HorizontalLayout hCabeceraGeneral;
	protected HorizontalLayout hCabeceraInicio;
	protected HorizontalLayout hCabeceraRegistrado;
	protected Button categoria;
	protected HorizontalLayout hDatosUserPerfil;
	protected VerticalLayout vDatosUsuario;
	protected HorizontalLayout hDatosSusVisit;
	protected Label nSuscriptores;
	protected Label nVisitas;
	protected Image imagen;
	protected Link apodo;
	protected Label nombre;
	protected Label apellidos;
	protected Label email;
	protected Label fNacimiento;
	protected HorizontalLayout hModificarDatos;
	protected Button modificarDatos;
	protected VerticalLayout vDatosPerfil;
	protected HorizontalLayout hApartados;
	protected Label videos;
	protected Label listaReproduccion;
	protected Label suscripciones;
	protected Label suscriptores;
	protected VerticalLayout vPanel;
	protected Panel panel;
	protected VerticalLayout vPanel1;
	protected HorizontalLayout hPanel;

	public Perfil_Propio_A_ventana() {
		Design.read(this);
	}
}
