package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Video2_ventana extends VerticalLayout {
	protected Label titulo;
	protected VerticalLayout vVideoGeneral;
	protected HorizontalLayout hVideo;
	protected Video video;
	protected VerticalLayout vAccionesVideo;
	protected Button modificarVideo;
	protected Button eliminarVideo;
	protected Link usuario;
	protected Label categoria;
	protected Label etiqueta;
	protected Label fechasubida;

	public Video2_ventana() {
		Design.read(this);
	}
}
