package Codigo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizacion_Video_Ajeno_ventana extends VerticalLayout {
	protected HorizontalLayout hCabeceraGeneral;
	protected HorizontalLayout hCabeceraGeneral2;
	protected HorizontalLayout hUserVideo;
	protected VerticalLayout datosUser;
	protected Image fotoUser;
	protected Link apodo;
	protected Label nVisualizaciones;
	protected Label nGusta;
	protected Label fechaSubida;
	protected VerticalLayout vVideoCompleto;
	protected HorizontalLayout hLabelVideo;
	protected Label tituloVideo;
	protected Label categoriaEtiqueta;
	protected VerticalLayout vvideo;
	protected Video video;
	protected TextArea descripcion;

	public Visualizacion_Video_Ajeno_ventana() {
		Design.read(this);
	}
}
